Fix data
openforcefield/protein-ligand-benchmark pull request #52
Opened 2022-05-09 22:47 UTC by bobym

Added newly prepped PDBs in `04_schrodinger` folders for each protein. Fixed invalid protein.pdb files.

2022-05-09 22:48 UTC, bobym commented
Note: I used the 3ELJ Jnk1 structure for this commit because original (PDB ID 2GMX) was NT.

2022-05-10 05:20 UTC, IAlibay commented
Would it be possible to get an overview of what the fix process was here? (it'll help review and probably we should have details for this written somewhere)

2022-05-10 16:13 UTC, dotsdl commented
@jchodera: should we be including annotations on what the biological unit (e.g. dimer) for each target is? Adding these 

@ppxasjsm: would like to run these through BioSimSpace; can try to operate on this branch before we merge this PR.

2022-05-10 16:48 UTC, bobym commented
> Would it be possible to get an overview of what the fix process was here? (it'll help review and probably we should have details for this written somewhere)

Absolutely -- I was including it in the draft of the paper but here's a brief overview of the prep in schrodinger:

> The co-crystal structures were prepared using Protein Prep Wizard1 in Schrödinger Suites (version 2021-1).  Bond orders were assigned, explicit hydrogens were added, and non-bridging waters (fewer than two H-bonds to non-waters) were removed. Het states were generated for pH 7.4 using Epik2. Hydrogen bonds were assigned and the protein was ionized using PROPKA at pH 7.4. A restrained minimization was performed using the OPLS4 force field3 to a heavy atom RMSD convergence of 0.3Å. For entries with multiple biological assemblies in their PDB, the assembly with the highest degree of coverage and lowest disorder was retained for use. The co-crystalized ligands were then removed from the protein.

2022-05-10 16:51 UTC, bobym commented
> @jchodera: should we be including annotations on what the biological unit (e.g. dimer) for each target is? Including these in `00` annotations would be the best place for this. The manuscript also needs a column in the table that lists these.
> 
> @ppxasjsm: would like to run these through BioSimSpace; can try to operate on this branch before we merge this PR.

@dotsdl As a heads up these are not aligned to the structures in `01_protein` so the ligands that are currently in the data folder will likely not be in the correct coordinates -- I'm docking the ligands now.

2022-05-10 17:09 UTC, IAlibay commented
> > Would it be possible to get an overview of what the fix process was here? (it'll help review and probably we should have details for this written somewhere)
> 
> Absolutely -- I was including it in the draft of the paper but here's a brief overview of the prep in schrodinger:
> 
> > The co-crystal structures were prepared using Protein Prep Wizard1 in Schrödinger Suites (version 2021-1).  Bond orders were assigned, explicit hydrogens were added, and non-bridging waters (fewer than two H-bonds to non-waters) were removed. Het states were generated for pH 7.4 using Epik2. Hydrogen bonds were assigned and the protein was ionized using PROPKA at pH 7.4. A restrained minimization was performed using the OPLS4 force field3 to a heavy atom RMSD convergence of 0.3Å. For entries with multiple biological assemblies in their PDB, the assembly with the highest degree of coverage and lowest disorder was retained for use. The co-crystalized ligands were then removed from the protein.

Thanks!

On a first pass I have two further points for clarification if that would be ok.

> The co-crystal structures

My understanding from what @jchodera has mentioned in the F@H alchemy meetings is that these are different starting crystals from what was previously used in this benchmark. Is that indeed the case? If so, would it be possible to know their provenance (if that's being added to the paper then just a pointer to the relevant place would be great).

>  non-bridging waters (fewer than two H-bonds to non-waters) were removed.

The previous directory structure was to split out the hetatm entries to a separate "cofactors_crystalwater.pdb" file rather than storing them in the protein.pdb file. Would it make sense to do so here too?

Also as a follow-up to this, are there any other cofactors that were retained (or thrown out) during the prep wizard procedure?

2022-05-10 17:11 UTC, IAlibay commented
> @ppxasjsm: would like to run these through BioSimSpace; can try to operate on this branch before we merge this PR.

@ppxasjsm am I correct in thinking that this will run things through tleap? I.e. this should indirectly address #9 ?

2022-05-11 19:51 UTC, j-wags commented
> @j-wags does it make sense to make sure openff's current alpha release can read these files too?

@IAlibay I think there's a good chance that the pre-alpha pdb parsing functionality still has significant bugs to shake out. So I wouldn't add it to CI just yet! I would have more confidence about it in a few months.

2022-05-24 16:09 UTC, dotsdl commented
We just merged #45, which adds two new targets `ros1` and `pde10`. Can you roll those targets and their ligands into the work in this PR?

2022-05-31 16:08 UTC, dotsdl commented
@IAlibay : won't begin review until [these comments](https://github.com/openforcefield/protein-ligand-benchmark/pull/52#issuecomment-1122657156) are addressed.

For reference, manuscript is here: https://github.com/openforcefield/FE-Benchmarks-Best-Practices

2022-05-31 16:19 UTC, dotsdl commented
@jchodera : @dotsdl will meet with @bobym in a working session to address remaining issues. Some ligands could not be docked with core constraints. Okay to permit those for Janssen sets; more concerning if these are JACS sets from Schrodinger.

Protonation states can be reviewed by others post-merge for correctness.

2022-05-31 22:00 UTC, bobym commented
As @jchodera mentioned some ligands are unable to be docked.  The PDE2 set was particularly bad (13/21 failed), I think due to poor structural similarity between the co-crystallized ligand and the docking set.  I used Glide SP with a ligand constraint utilizing the maximum common substructure relative to the co-crystalized ligand (with a 0.1Å RMSD allowance). I'm rerunning the docking with an allowance of 0.25Å and the alternative crystal structures mentioned below to see if this will allow us to keep more ligands. 

If there continues to be a large number of ligands that are unable to be docked (from the JACS sets at least), we might need to explore equilibrating/relaxing the structures prior to docking. 

@dotsdl regarding comments:

> On a first pass I have two further points for clarification if that would be ok.
> 
> > The co-crystal structures
> 
> My understanding from what @jchodera has mentioned in the F@H alchemy meetings is that these are different starting crystals from what was previously used in this benchmark. Is that indeed the case? If so, would it be possible to know their provenance (if that's being added to the paper then just a pointer to the relevant place would be great).

A few of these are going to be different starting crystals from what was previously used. Specifically JNK1 (starting crystal 2GMX was not trustworthy) and PDE2 (starting crystal had very low ligand similarity). Will update with exactly which structures were used.

> > non-bridging waters (fewer than two H-bonds to non-waters) were removed.
> 
> The previous directory structure was to split out the hetatm entries to a separate "cofactors_crystalwater.pdb" file rather than storing them in the protein.pdb file. Would it make sense to do so here too?

I discussed this with @jchodera and we had decided that it would be fine to include the waters and cofactors in the protein.pdb file while providing the ligand(s) as a separate sdf.

> Also as a follow-up to this, are there any other cofactors that were retained (or thrown out) during the prep wizard procedure?

I've largely retained any cofactors present (ions, AMP, etc) but did remove solvent hets that are not water (like glycerol). I'll make note of this in the methods.

2022-05-31 22:42 UTC, IAlibay commented
> I discussed this with @jchodera and we had decided that it would be fine to include the waters and cofactors in the protein.pdb file while providing the ligand(s) as a separate sdf.

This might be something that needs further discussion. Personally I don't have a strong opinion on the removal of `cofactors_crystalwater.pdb`. However if we go down that route, we should be loud about the change in the docs (there's at least the readme and the docs/file_tree.txt which need updating?).

That being said, folks often have different views on what to keep / remove parts of an original crystal. I would ask if we can either a) keep the "discarded" parts of the crystal as an additional pdb file, or b) the original PDB file used (or at least a reference to them that doesn't involve grepping from the PDB header) in the data folders. Probably the latter makes more sense if the new `protein.pdb` files have been discarded.

On a separate point to all this, I'm just having a quick look at the files and I'm noticing non-deduplicated altLocs for some of the proteins. For example:

https://github.com/openforcefield/protein-ligand-benchmark/blob/7718225acb0a3117ea557e950e24b58b07fd4f42/data/2020-08-12_tnks2/04_schrodinger/protein.pdb#L1005-L1017

I suspect I might be looking at the wrong files (otherwise I'm surprised the system even minimized as is!), but if not, we should make a decision on which state to keep here?

2022-06-02 15:10 UTC, dotsdl commented
From discussion with @bobym, previously it was necessary to have the protein separate from the cofactors and crystal waters for for GROMACS use. If this is still the case we're inclined to keep them separate; if it is *not*, we'd like to simplify and keep cofactors and waters together with the protein as the collective "target".

2022-06-02 17:16 UTC, IAlibay commented
> From discussion with @bobym, previously it was necessary to have the protein separate from the cofactors and crystal waters for for GROMACS use. If this is still the case we're inclined to keep them separate; if it is _not_, we'd like to simplify and keep cofactors and waters together with the protein as the collective "target".

The need to separate out the protein from "things which pdb2gmx doesn't like" (i.e. non-waters, non-protein) remains if you want to use it within gromacs. Now this doesn't mean that we can't ask for folks downstream to filter out the pdb, but if we wanted to double check against existing workflows that a step we need to ask folks to do.

My 2 cent here is that we should be following whatever OpenFF is likely to be able to read in a stable manner in the next couple of months. If OpenFF can't read a PDB + non-water cofactors in one go, then we should consider what steps would be required to take these files and load them into OpenMM.

2022-06-02 17:45 UTC, dotsdl commented
Thank you @bobym for the call today!

Sharing update from the meeting here:

@bobym will push targets with altLoc choices later today, along with docked ligands and documented procedure for preparing both. 

Not all ligands were able to be successfully docked; between 460 and 480 were able to be docked, out of 524 in the set. Once we have these here, we can offer feedback and decide how to proceed given the procedure and its outputs. @IAlibay and I will perform independent checks on the PDBs, SDFs as part of the feedback cycle.

@bobym apologies, I meant to mention: we now also have `pde10`, which is present among the targets under `2020-07-10_pde10/`. Is it possible to run the same treatment on this target and its ligands? This was finalized yesterday as part of the [0.2.1 release](https://github.com/openforcefield/protein-ligand-benchmark/releases/tag/0.2.1) so it's a recent addition officially.

2022-06-03 05:09 UTC, bobym commented
> @bobym will push targets with altLoc choices later today, along with docked ligands and documented procedure for preparing both.

I'll push all of this Friday morning -- there was a problem with the file export from Schrodinger.

> Not all ligands were able to be successfully docked; between 460 and 480 were able to be docked, out of 524 in the set. Once we have these here, we can offer feedback and decide how to proceed given the procedure and its outputs. @IAlibay and I will perform independent checks on the PDBs, SDFs as part of the feedback cycle.

Currently have 440/505 ligands (excluding Galectin and JNK1, which were unable to dock at all).

> @bobym apologies, I meant to mention: we now also have `pde10`, which is present among the targets under `2020-07-10_pde10/`. Is it possible to run the same treatment on this target and its ligands? This was finalized yesterday as part of the [0.2.1 release](https://github.com/openforcefield/protein-ligand-benchmark/releases/tag/0.2.1) so it's a recent addition officially.

Happy to prep and add this.

2022-06-03 18:55 UTC, bobym commented
@IAlibay  @dotsdl I pushed the updated PDBs (with commits for alt locs) in in `01_protein` for each target. Ligands are as a single sdf in `02_ligands`. 

Some issues:
Thrombin ligands are not included because the ligands were unable to dock. I'm still looking at this and the dropped ligands from other targets. 

JNK1 was dropped entirely for now -- original structure was not trustworthy and the alternatives have poor overlap with ligand set.

PDE2 crystal was changed from 6EZF to 6C7E. 

Commentary on prep: (unsure where to put this in the repo):
![image](https://user-images.githubusercontent.com/44821087/171930115-16a6f3a6-fe30-4c88-9299-fee7eabd3bd7.png)

2022-06-04 01:04 UTC, dotsdl commented
Excellent, thank you @bobym! Checking these out on my end now. I'm also happy to take care of moving things around, splitting up ligands, etc.

Can you post the procedure as plaintext, perhaps in a comment here? I won't be able to use a screenshot for including it in this PR.

2022-06-04 02:33 UTC, dotsdl commented
Thanks again @bobym for all this work! I've finished my initial review. Will return to this on Monday. Notes below:

1. We'll need the same treatment for `pde10` as for the other targets. I've added its PDB on top of the LFS smudge file that was present in its place.
2. It looks like we don't have any ligands for `bace`; is this expected?
3. It looks like the PDBs for `tyk2` and `tnks2` are identical. It looks like `tyk2` should have a PDB file based on 4GIH, not 4UI5.

I left `jnk1`, `galectin`, `pde10`, and `bace` out of my analysis given the issues raised above and earlier. The notebook for my analysis is given below.

[PR-52.zip](https://github.com/openforcefield/protein-ligand-benchmark/files/8836657/PR-52.zip)

2022-06-06 18:03 UTC, bobym commented
> 1. We'll need the same treatment for `pde10` as for the other targets. I've added its PDB on top of the LFS smudge file that was present in its place.

On it now! I'll push is ASAP along with the text file for the prep work methods.
.
> 2. It looks like we don't have any ligands for `bace`; is this expected?

That was not expected -- I think it was a problem with conversion from the .sdfgz to .sdf. I've pushed a fixed file that actually has ligands.

> 3. It looks like the PDBs for `tyk2` and `tnks2` are identical. It looks like `tyk2` should have a PDB file based on 4GIH, not 4UI5.
Also pushed the correct file for this. My mistake when I was moving the files around. 

> I left `jnk1`, `galectin`, `pde10`, and `bace` out of my analysis given the issues raised above and earlier. The notebook for my analysis is given below.
> 
> [PR-52.zip](https://github.com/openforcefield/protein-ligand-benchmark/files/8836657/PR-52.zip)

2022-06-07 00:46 UTC, dotsdl commented
Excellent, thank you @bobym! Including both `pde10` and `bace` in my analysis yields good results for both. I now see only one outstanding issue:

1. The PDB file for `tnks2` at `2020-08-12_tnks2']['01_protein/crd/protein.pdb` contains what looks like two more hydrogens than it should. These are atoms 2598, 2599 in the file. Removing these gives the expected count of hydrogens in the histidine residue (resid 1117). I'm not sure if this is the right solution, however, and would rather we identify why these are here.

If we can solve this issue, I'm happy to take on populating the individual ligand SDF files and making any other cosmetic changes.

Some additional questions for clarification:

1. I see all 11 `thrombin` ligands represented; were you able to dock these? They don't show any clashes in my analysis, and they look well aligned.
2. Besides `pde2`, are there any other targets for which we chose a change in crystal structure?

Some conclusions:

1. Let's proceed with dropping `jnk1` and `galectin` in this PR. This satisfies part of #31. If we are also still having issues with `thrombin`, let's remove it in this PR as well.
2. @IAlibay, @jchodera: if we switch our choice of PDB for `pde2` to the `alternate` structure, should we alter the [`references`](https://github.com/openforcefield/protein-ligand-benchmark/blob/202ae6a40a49860d9f50eac6705f29717fcf2559/data/2019-09-23_pde2/00_data/target.yml#L15-L21) as well, or do those still reasonably apply?

2022-06-07 01:20 UTC, dotsdl commented
Finished a thorough analysis of ligand structure alignment; getting some odd results for e.g. `hif2a`. Notebook is attached.

@IAlibay do you see the same issue, or is there something wrong with my analysis code?

[PR-52.zip](https://github.com/openforcefield/protein-ligand-benchmark/files/8849260/PR-52.zip)

2022-06-07 14:47 UTC, dotsdl commented
As it stands, this PR will close #37, #24, and #53. It will partially close #31.

2022-06-08 05:13 UTC, dotsdl commented
Looks excellent @bobym! I don't detect any more clash issues.

I found the issue in my analysis for `hif2a`: the ligand MCS happens to have two matches within the molecule for a couple of the ligands, and we probably end up choosing one or the other at random in our selection. This is why the RMSDs are so bad for 2 out of 36 ligands compared to the reference, but not for others, in my analysis.

However, for `pde10` I see two ligands, `lig_5687` and `lig_1801` (MCS RMSD 7.99A, 7.87A, respectively), with very poor alignment to the others. Is this expected?

2022-06-10 23:06 UTC, bobym commented
> I found the issue in my analysis for `hif2a`: the ligand MCS happens to have two matches within the molecule for a couple of the ligands, and we probably end up choosing one or the other at random in our selection. This is why the RMSDs are so bad for 2 out of 36 ligands compared to the reference, but not for others, in my analysis.

That makes sense -- I can try to write out the core constraint manually such that it wouldn't match and see if that solves the problem. Which ligands are you seeing this with?

> However, for `pde10` I see two ligands, `lig_5687` and `lig_1801` (MCS RMSD 7.99A, 7.87A, respectively, relative to `lig_0309`), with very poor alignment to the others. Is this expected?

I would not have expected this and i'm not sure why it's doing it based on what I'm seeing in the log files. I've pushed a set of re-docked ligands where I manually defined the core instead of using the MCS. This seems to have fixed the problem for 'lig_5687', but 'lig_1801' drops out because it fails after energy minimization. Another ligand however was able to be docked, bringing this set up to 35/36 successfully docked.

2022-06-11 05:51 UTC, dotsdl commented
> > I found the issue in my analysis for `hif2a`: the ligand MCS happens to have two matches within the molecule for a couple of the ligands, and we probably end up choosing one or the other at random in our selection. This is why the RMSDs are so bad for 2 out of 36 ligands compared to the reference, but not for others, in my analysis.
> 
> @dotsdl That makes sense -- I can try to write out the core constraint manually such that it wouldn't match and see if that solves the problem. Which ligands are you seeing this with?
> 

Ah sorry @bobym, I meant to clarify here that there is no problem with the ligand alignments for `hif2a` as far as I can tell. My analysis was giving a false alarm due to there being two substructures within a couple ligands that match the MCS. Nothing to worry about on that front. :grin: 

> > However, for `pde10` I see two ligands, `lig_5687` and `lig_1801` (MCS RMSD 7.99A, 7.87A, respectively, relative to `lig_0309`), with very poor alignment to the others. Is this expected?
> 
> I would not have expected this and i'm not sure why it's doing it based on what I'm seeing in the log files. I've pushed a set of re-docked ligands where I manually defined the core instead of using the MCS. This seems to have fixed the problem for 'lig_5687', but 'lig_1801' drops out because it fails after energy minimization. Another ligand however was able to be docked, bringing this set up to 35/36 successfully docked.

Excellent, taking a look! Thank you!

2022-06-12 18:26 UTC, dotsdl commented
Looks great @bobym! I don't observe any additional issues with the ligands.

I have pushed separated ligand files for each targets, and retained the `ligands.sdf` you created in the `02_ligands` directory for each target.

@jchodera and @IAlibay, when you can, please give what we've done here an independent review. 

I will next be removing all gromacs-specific files from the data files.

2022-06-17 18:52 UTC, jchodera commented
@bobym and I are looking through this right now. 
@dotsdl when you're back, can you work directly with @bobym to clean everything up?

TODO:
- [ ] delete [2019-09-23_jnk1/04_schrodinger](https://github.com/openforcefield/protein-ligand-benchmark/tree/fix_data/data/2019-09-23_jnk1/04_schrodinger) since we have to drop JNK1
- [ ] remove all `04_schrodinger/` directories
- [ ] move `protein.pdb` into `01_protein/`
- [ ] remove all old stuff :`01_protein/top`, `02_ligands/lig_*`, `03_hybrid/`
- [ ] get rid of the dates in target name directories--they are meaningless and belong in the metadata if anything (e.g. [2019-12-13_mcl1](https://github.com/openforcefield/protein-ligand-benchmark/tree/fix_data/data/2019-12-13_mcl1))

2022-06-22 15:09 UTC, dotsdl commented
@jchodera I'm back, and will proceed on this list today. Thanks for your review!

2022-06-23 07:09 UTC, dotsdl commented
@jchodera completed the items you and @bobym listed. I also did:
- [x] update each `ligands.yml` file to include only ligands that could be docked
- [x] remove jnk1 and galectin

@IAlibay can we work together on generating new atom maps via Lomap for each edge?

2022-06-27 21:20 UTC, ijpulidos commented
Is there any special reason why we prefer having an `sdf` file for each ligand instead of having all of them in a single `ligands.sdf` file? I guess not having to sync between them both is a reason, but I think as long as the names or identifiers in the `sdf` file correspond to the ones in the `ligands.yaml` file, we should be okay, we wouldn't even require them to be in the same order. Does that make sense?

2022-06-27 21:34 UTC, IAlibay commented
> @ijpulidos In addition to the issues listed above, it occurred to me that there are some ligands that were unable to be docked which I don't think have been removed from the ligands.yaml file yet. @dotsdl Do we have a preferred way to do handle this?

my 2 cent here is that if the ligands aren't there we should remove them from the yaml files (and add them back if/when we can place them back in the benchmark), otherwise we just have empty references to things which aren't "in the benchmark"

If we go down this route we should do this at the same time as the mapping generation?

2022-06-27 23:01 UTC, dotsdl commented
@bobym I [already removed the ligands that weren't included in the `ligands.sdf` file for each target from each `ligands.yml` file](https://github.com/openforcefield/protein-ligand-benchmark/pull/52#issuecomment-1164035759) in commit 089858cdfe9173ab23f7def551fe1efb2069b573, so we should be good there!

2022-06-27 23:02 UTC, dotsdl commented
And @ijpulidos, as @IAlibay pointed out, I'm going off of what I took to be some consensus around @j-wags [comment here](https://github.com/openforcefield/protein-ligand-benchmark/issues/53#issuecomment-1136473003).

2022-06-29 15:31 UTC, IAlibay requested changes
A review of the current PDB contents (for further discussion with Dotston later this afternoon).

A lot of the points I'm making here are based on the idea that the aim we have decided upon during the F@H was that these files should be as easy as possible to pass through to various tools for parameterisation.

For now, it looks like most things will get ingested by OpenMM reasonably, however there are changes we can make here to make life easier for everyone down the line.


**Easy things we could do for this release:**
1. Rename NMA to NME: The standard naming for N-Methyl caps is NME, indeed AMBER's leap will complain if you pass NMA through (see `$AMBERHOME/dat/leap/lib/aminoct12.lib` for more details). Given that NME is widely supported, I would suggest renaming as such.
2. Don't have give NMA be an icode entry: this is pretty much playing with fire, icodes are part of the PDB standard (and I love using them to test whether folks are PDB compliant), but we definitely know most things don't treat them properly.
3. Caps should bet HETATM records not ATOM records: this is one of the weird places where some folks actually care about the distinction between standard and non-standard residues. - Note: AMBER & OpenFF do not fail here, it's just a matter of a quick change we can make to close in on the PDB standard.
4. ANISOU records: they aren't very consistent currently (see BACE's pdb). Honestly whilst I get their potential use, unless schrodinger does something with them they probably aren't very useful on a post-optimised structure. Whilst tleap doesn't complain about them, I'm pretty sure some tools will, removing them has zero cost and would make future life a lot easier.

**Things that are harder and might need to be done in the next release:**
5. Residue naming: because we are explicitly including hydrogens, we are getting to a point where sticking to standard residue names is going to hurt us.
  5.1 CYX: There are known SSBOND entries in many of these PDBs. If we don't explicitly identify the disulfide bridges we run the risk of downstream tools just ignoring the SSBOND entries (not checked what OpenMM does here, I hope it's better than tleap, but also in many ways if I pass a CYS I kinda expect a CYS not a CYX). edit: It's possible that just sticking to making sure these are in the CONECT record _might_ be fine here (I know that's fine for tleap, I can't remember about pdb2gmx off the top of my head)
  5.2 I'm getting a lot things like "Created a new atom named: HD1 within residue: .R<HIE 206>" - looks to me like we have several cases where we have protonated residues which still assigned to the canonical residue name. This is definitely going to cause some issue. I would suggest we actually explicitly name our residues using the AMBER style convention here to make it very clear where our protonated residues and knowing that most tools won't get confused.
  5.3 I'm getting some hydrogens name "H1" in the residues directly next to the ACE caps, I'm not sure what's up here, but I'm pretty sure they should be called "H"?
  5.4 Linked to the above, I'm getting errors regarding a hydrogen named "H" being present on the ACE residues. At least on the AMBER lib side of things - those are expected to be called H1, H2, and H3.
6. This is just a note - I've seen cases where negative numbers can lead to undefined behaviour for residue numbers. It doesn't break anything I can see right now, but we might want to consider if we should just lose the original information and make everything start at 1.
7. Given last week's F@H discussion on the biopolymer stuff (i.e. the fact that for now things will be solely "pass in one polymer to parameterise"). Could we please consider moving the things which aren't protein, water or ions to a separate SDF file? This would make life immensely more easy for folks as we could just pick it up directly with the OpenFF tk and parameterise it directly with parsley & not have to rely on a) post-process identifying non-standard components, b) bond order perception from a PDB file.

2022-06-29 16:38 UTC, dotsdl commented
@jchodera do you have any strong opinions on the points raised by @IAlibay above?

2022-06-29 17:21 UTC, ijpulidos commented
> 5.1 CYX: There are known SSBOND entries in many of these PDBs. If we don't explicitly identify the disulfide bridges we run the risk of downstream tools just ignoring the SSBOND entries (not checked what OpenMM does here, I hope it's better than tleap, but also in many ways if I pass a CYS I kinda expect a CYS not a CYX). edit: It's possible that just sticking to making sure these are in the CONECT record _might_ be fine here (I know that's fine for tleap, I can't remember about pdb2gmx off the top of my head) 

My 2 cents. I think  we should try to stick with using `SSBOND` or `CONECT` entries, rather than relying on `CYX`. I think the latter is only a thing in the Amber world, whereas the others are part of the PDB  specification. I checked with Openmm's `PDBFile` and it can handle SSBOND entries correctly, that is, the topology object has a bond between the cysteines (sulfur atoms) specified in the `SSBOND` entries.

2022-06-29 17:53 UTC, IAlibay commented
> My 2 cents. I think we should try to stick with using SSBOND or CONECT entries,


> > 5.1 CYX: There are known SSBOND entries in many of these PDBs. If we don't explicitly identify the disulfide bridges we run the risk of downstream tools just ignoring the SSBOND entries (not checked what OpenMM does here, I hope it's better than tleap, but also in many ways if I pass a CYS I kinda expect a CYS not a CYX). edit: It's possible that just sticking to making sure these are in the CONECT record _might_ be fine here (I know that's fine for tleap, I can't remember about pdb2gmx off the top of my head)
> 
> My 2 cents. I think we should try to stick with using `SSBOND` or `CONECT` entries, rather than relying on `CYX`. I think the latter is only a thing in the Amber world, whereas the others are part of the PDB specification. I checked with Openmm's `PDBFile` and it can handle SSBOND entries correctly, that is, the topology object has a bond between the cysteines (sulfur atoms) specified in the `SSBOND` entries.

@ijpulidos 

I was just about to agree and then realised that tleap does not like this with just being defined in CONECT so I'm going to change my mind.

We don't live in an OpenMM isolated world. Plenty of folks use tleap, including BioSimSpace (who's interest are directly represented here). If CYX works for everything then I see no reason to no make the change, it'd be weird to have known failures for some of our readers but not others?

Also given that part of the discussion here is that we have to consider what to do with protonated residues, it makes no sense to have HID residues but not CYX.

**TLDR;** The main point I'm making is the following: if we decide to be PDB standard compliant then fine, but then we need to be fully standard compliant (which means reviewing these files based on that point), and it means that we know that we'll fail for some readers - which is different than what I understood we agreed to set out to do in the F@H alchemy meetings.

2022-07-01 05:19 UTC, jchodera commented
@IAlibay : Thanks for the detailed review! Tagging in @bobym here, though @ijpulidos can help remediate these files as he uncovers additional issues.

Some comments below:

> Easy things we could do for this release:
> Rename NMA to NME: The standard naming for N-Methyl caps is NME, indeed AMBER's leap will complain if you pass NMA through (see $AMBERHOME/dat/leap/lib/aminoct12.lib for more details). Given that NME is widely supported, I would suggest renaming as such.

Agree. We need to stick to the PDB standard, and ideally a minimal subset that is maximally compatible.

> Don't give NMA be an icode entry: this is pretty much playing with fire, icodes are part of the PDB standard (and I love using them to test whether folks are PDB compliant), but we definitely know most things don't treat them properly.

Agree. We should keep to the minimal subset of the PDB standard to maximize compatibility.

> Caps should bet HETATM records not ATOM records: this is one of the weird places where some folks actually care about the distinction between standard and non-standard residues. - Note: AMBER & OpenFF do not fail here, it's just a matter of a quick change we can make to close in on "correctness" of the PDB standard.

Agree. We need to stick to the PDB standard here. Cap residues that are not part of the [standard amino acids and nucleotides](https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) should be designated `HETATM` and include `CONECT` records.

> ANISOU records: they aren't very consistent currently (see BACE's pdb). Honestly whilst I get their potential use, unless schrodinger does something with them they probably aren't very useful on a post-optimised structure. Whilst tleap doesn't complain about them, I'm pretty sure some tools will, removing them has zero cost and would make future life a lot easier.

Agree. Removing `ANISOU` records will help us keep to the minimal subset of the PDB standard to maximize compatibility.

> Things that are harder and might need to be done in the next release with the idea that we won't be able to support non-OpenMM things in 0.3.0:
> Residue naming: because we are explicitly including hydrogens, we are getting to a point where sticking to standard residue names is going to hurt us.
> 5.1 CYX: There are known SSBOND entries in many of these PDBs. If we don't explicitly identify the disulfide bridges we run the risk of downstream tools just ignoring the SSBOND entries (not checked what OpenMM does here, I hope it's better than tleap, but also in many ways if I pass a CYS I kinda expect a CYS not a CYX). edit: It's possible that just sticking to making sure these are in the CONECT record might be fine here (I know that's fine for tleap, I can't remember about pdb2gmx off the top of my head)

Here, we need to adhere to the PDB standard regarding the naming of residues and designation of disulfide bonds via _both_ `SSBOND` and `CONECT` records. We should _not_ use nonstandard residue names.

> 5.2 I'm getting a lot things like "Created a new atom named: HD1 within residue: .R<HIE 206>" - looks to me like we have several cases where we have protonated residues which still assigned to the canonical residue name. This is definitely going to cause some issue. I would suggest we actually explicitly name our residues using the AMBER style convention here to make it very clear where our protonated residues and knowing that most tools won't get confused.
> 5.3 I'm getting some hydrogens name "H1" in the residues directly next to the ACE caps, I'm not sure what's up here, but I'm pretty sure they should be called "H"?
> 5.4 Linked to the above, I'm getting errors regarding a hydrogen named "H" being present on the ACE residues. At least on the AMBER lib side of things - those are expected to be called H1, H2, and H3.

I presume you mean you're running LEaP, which uses atom and residue names, without first having run `pdb4amber`, and it generated these errors?

The [Amber reference manual](https://ambermd.org/doc12/Amber22.pdf) Section 12 clearly specifies how PDB files are to be prepared for AMBER. This section recommends running the provided `pdb4amber` and `reduce` tools to produce a file that can be parsed by the LEaP toolchain. Since the manual recommends this as the "correct" approach to bringing standard PDB files into the AMBER toolchain, can we agree that we just need the input files to work witht his process?

> This is just a note - I've seen cases where negative numbers can lead to undefined behaviour for residue numbers. It doesn't break anything I can see right now, but we might want to consider if we should just lose the original information and make everything start at 1.

The recommended `pdb4amber` tool renumbers residues sequentially starting at 1. We should not do that for the standard PDB files we provide, since this will make it more complicated to debug any issues or understand the provenance of these files.

> Given last week's F@H discussion on the biopolymer stuff (i.e. the fact that for now things will be solely "pass in one polymer to parameterise"). Could we please consider moving the things which aren't protein, water or ions to a separate SDF file? This would make life immensely more easy for folks as we could just pick it up directly with the OpenFF tk and parameterise it directly with parsley & not have to rely on a) post-process identifying non-standard components, b) bond order perception from a PDB file.

I agree that it would be best to move any cofactors to a separate `cofactors.sdf` file for now.

The OpenFF biopolymer limitation is surprising---all of the information for all heterogens in the PDB is available in the Ligand  Expo, so I'm not sure why we shouldn't be making use of _all_ of that information if we are making use of some of it.

2022-07-01 15:56 UTC, ijpulidos commented
> I checked with Openmm's `PDBFile` and it can handle SSBOND entries correctly, that is, the topology object has a bond between the cysteines (sulfur atoms) specified in the `SSBOND` entries.

I have to correct myself here. OpenMM doesn't handle the `SSBOND` entries directly but rather it identifies disulfide bonds using proximity with the `createDisulfideBonds` method.

2022-07-03 22:43 UTC, jchodera commented
> I have to correct myself here. OpenMM doesn't handle the SSBOND entries directly but rather it identifies disulfide bonds using proximity with the createDisulfideBonds method.

You're right---that might be a bug, since the [PDB format requires `CONECT` records to be present if both `SG` atoms are present](https://www.wwpdb.org/documentation/file-format-content/format33/sect6.html).

2022-07-12 15:30 UTC, IAlibay commented
@bobym @dotsdl @jchodera 

I'm going through the thrombin entry for #58 and I'm noticing that there are caps on both termini of chain `I`. However the PDB entry only identifies a missing residue at `LEU I 64`. Just checking if we really want that `ACE` cap in there or if that termini _should_ be charged? I've not verified the sequence against uniprot.

2022-07-12 15:55 UTC, IAlibay commented
Also for some reason there are still altloc entries for some of the proteins; definitely for thrombin, need to re-check the other proteins.

2022-07-13 13:03 UTC, ijpulidos commented
I tried running the `cdk2` data set and there are some ligands missing in the data. Namely, ligands 'lig_28', 'lig_29', 'lig_30', 'lig_31', 'lig_32', and 'lig_1h1s', are missing. These are part of the [edges.yml file](https://github.com/openforcefield/protein-ligand-benchmark/blob/fix_data/data/cdk2/00_data/edges.yml) but they don't have any `sdf` files in the [ligands directory](https://github.com/openforcefield/protein-ligand-benchmark/tree/fix_data/data/cdk2/02_ligands).

Do these correspond to ligands that could not be docked? Or any ideas why they are missing?

2022-07-13 23:18 UTC, IAlibay commented
Here's another one on the list of issues - the presence of bonds in the CONECT records is not consistent.

Using MCL1 as an example; we have:
  - bonds defined for the ACE C-H connections as part of the methyl group. But nothing for the C-C or C-O bonds.
  - no bonds defined for the NMA / NME cap
  - explicit bonds defined for all the waters

2022-07-14 07:04 UTC, jchodera commented
>
> Here's another one on the list of issues - the presence of bonds in the
> CONECT records is not consistent.
>
> Using MCL1 as an example; we have:
>
>    - bonds defined for the ACE C-H connections as part of the methyl
>    group. But nothing for the C-C or C-O bonds.
>    - no bonds defined for the NMA / NME cap
>    - explicit bonds defined for all the waters
>
> That is indeed problematic!

Melissa: Is this a general feature of Maestro's PDB export? If so, this
should probably be reported as a bug.

I wonder if we have to run these through Spruce anyway to make the outputs
consistent and PDB compliant...

>
>    -
>
>

2022-07-14 18:27 UTC, IAlibay commented
> I wonder if we have to run these through Spruce anyway to make the outputs consistent and PDB compliant...

@jchodera (and also copying @dotsdl here)

Re-creating and re-evaluating a new set of PDB files is definitely a non-insignificant amount of work. With the interest of "getting files ready for immediate use", would we be happy to stick with the current files (+ the changes proposed in #58) for 0.3.0 and then go through another round of re-working through the files for 0.4.0 and beyond? The idea being that the files may be imperfect but at least OpenMM interprets things as intended (note: this is something we need to double check before we cut the release).

There's still a ton of additional work that we haven't really done here (and I don't think we'll have time to look at any time soon), such manually double checking protonation states and accounting for differences from the original dataset. So I'm hoping we don't mind if these files (and the intended models generated) change again in a future release?

2022-07-14 19:13 UTC, j-wags commented
> There's still a ton of additional work that we haven't really done here (and I don't think we'll have time to look at any time soon), such manually double checking protonation states and accounting for differences from the original dataset. So I'm hoping we don't mind if these files (and the intended models generated) change again in a future release?

Yes, my current thinking is that we should get the MVP going here to satisfy the technical needs of OpenFE+Chodera lab+OpenFF, and if we later find that we lost important knowledge from the original set (or we just stop being in such a time-deficit), we can do another round of cleanup. But I agree that that's "a ton" of work. Having a dataset be "reproducible" and having it be "guided by expert input" are nearly opposites. It will be a ton of work to satisfy both so we should be deliberate about committing to both.

2022-07-14 20:50 UTC, bobym commented
>I'm going through the thrombin entry for https://github.com/openforcefield/protein-ligand-benchmark/pull/58 and I'm noticing that there are caps on both termini of chain I. However the PDB entry only identifies a missing residue at LEU I 64. Just checking if we really want that ACE cap in there or if that termini should be charged? I've not verified the sequence against uniprot.

@IAlibay This is a good question. I think what's going on here is that because PDB 2ZFF has these residues as their own chain (I), the missing residue isn't captured by the process used to add missing residues/loops. I'm not sure that Spruce would catch it either -- how should we handle that?

> Also for some reason there are still altloc entries for some of the proteins; definitely for thrombin, need to re-check the other proteins. -- @bobym can I check that the intended strategy here is to retain A? If so I'll fix in #58.
> 
> Edit: can confirm this only affects thrombin.

@IAlibay This is my fault -- I uploaded the un-confirmed altloc file. The intended strategy is to retain A. I can push the correct one ASAP, just want to make sure the folder paths are still the same or did the naming change accoring to @jchodera's To-Do?

>move protein.pdb into 01_protein/
> remove all old stuff :01_protein/top, 02_ligands/lig_*, 03_hybrid/
>get rid of the dates in target name directories--they are meaningless and belong in the metadata if anything (e.g. [2019-12-13_mcl1](https://github.com/openforcefield/protein-ligand-benchmark/tree/fix_data/data/2019-12-13_mcl1)) and update targets.yml

> Melissa: Is this a general feature of Maestro's PDB export? If so, this should probably be reported as a bug.
@jchodera As far as I can tell, there is no option to not have this happen. The only option they provide for exporting to PDB regarding the CONECT records is whether or not you use duplicate CONECT records for double bonds.

2022-07-14 20:55 UTC, bobym commented
> I tried running the `cdk2` data set and there are some ligands missing in the data. Namely, ligands `lig_28`, `lig_29`, `lig_30`, `lig_31`, `lig_32`, and `lig_1h1s`, are missing. These are part of the [edges.yml file](https://github.com/openforcefield/protein-ligand-benchmark/blob/fix_data/data/cdk2/00_data/edges.yml) but they don't have any `sdf` files in the [ligands directory](https://github.com/openforcefield/protein-ligand-benchmark/tree/fix_data/data/cdk2/02_ligands).
> 
> Do these correspond to ligands that could not be docked? Or any ideas why they are missing?

@ijpulidos These correspond to the ligands that were not able to be docked. This occurred across several targets with varying degrees of dropout. If it's helpful, I can provide a file showing which ligands were unable to be docked?

2022-07-14 21:08 UTC, IAlibay commented
@bobym 

> This is a good question. I think what's going on here is that because PDB 2ZFF has these residues as their own chain (I), the missing residue isn't captured by the process used to add missing residues/loops. I'm not sure that Spruce would catch it either -- how should we handle that?

The missing residues is probably a separate problem, which should be addressed if there is an issue here. The main question I wanted to bring here is whether or not peptides should have caps. Although chain `I` isn't too close to the binding site, it's not so far that it couldn't influence side chains on the periphery of the binding sites. Our choice of charged vs capped termini can be quite influencal to reproducing the intended behavior of a system.

> @IAlibay This is my fault -- I uploaded the un-confirmed altloc file. The intended strategy is to retain A. I can push the correct one ASAP, just want to make sure the folder paths are still the same or did the naming change accoring to @jchodera's To-Do?

Are there any other changes to this file aside from the altlocs? If not then I've already made the changes in #58 (I had to re-process the whole file with MDAnalysis anyways).

2022-07-14 21:19 UTC, bobym commented
> > e missing residue isn't captured by the process used to add missing residues/loops. I'm not sure that Spruce would catch it either -- how should we handle that?
> 
> The missing residues is probably a separate problem, which should be addressed if there is an issue here. The main question I wanted to bring here is whether or not peptides should have caps. Although chain `I` isn't too close to the binding site, it's not so far that it couldn't influence side chains on the periphery of the binding sites. Our choice of charged vs capped termini can be quite influencal to reproducing the intended behavior of a system.
> 
> > @IAlibay This is my fault -- I uploaded the un-confirmed altloc file. The intended strategy is to retain A. I can push the correct one ASAP, just want to make sure the folder paths are still the same or did the naming change accoring to @jchodera's To-Do?
> 
> Are there any other changes to this file aside from the altlocs? If not then I've already made the changes in #58 (I had to re-process the whole file with MDAnalysis anyways).

@IAlibay No, no other changes.

As it currently stands in the paper, we suggest capping the ends of gaps.

> This "capping" tactic can also treat the termini of"gaps": regions of missing residues over the span of the peptide chain, usually missing loop regions due to lack of experimental density. While capping the ends of a loop instead of modeling the whole loop may be acceptable for MD runs of relatively short duration, over longer simulations there is a risk of having the protein around the capped ends of the missing loop gradually lose its structure.

That said, chain I is actually Hirudin variant-1 -- not actually a part of the structure of thrombin itself. I don't think it's unreasonable to remove it in it entirety, but if we were to do that, we could use a different structure all together that doesn't have the Hirudin.

2022-07-14 21:27 UTC, IAlibay commented
> As it currently stands in the paper, we suggest capping the ends of gaps.

I might be misunderstanding the intent here, but my interpretation of that text is that neither Chain L or I count gaps of the main protein chain?

2022-07-14 22:16 UTC, bobym commented
> I might be misunderstanding the intent here, but my interpretation of that text is that neither Chain L or I count gaps of the main protein chain?

Ah, yes I see what you're saying. I was the one misunderstanding what you were saying. You're right -- they're not gaps of the main chain. That said, the missing L64 is actually the unmodeled terminus of the peptide, so I think that should be capped according to the paper? @jchodera do you have thoughts about whether short peptides should be treated differently than whole monomers?

This actually raises another question: we suggest capping termini if they aren't resolved. In the case of CDK2 (pdb 1H1Q), it's a dimer with CDK2 and cyclin A2. CDK2 has unresolved termini, but cyclin A2 doesn't -- should both structures be capped? Just the CDK2 monomer?

2022-07-15 10:24 UTC, jchodera commented
My understanding was that truncation to termini not used in the assay or
biological construct should always result in capping of that chain.

The main open question is whether "trivial" omissions of a few residues
should be modeled if possible to do so, and how many residues are allowed
to be modeled. For internal short loops, I imagine it is optimal to model
them in if unambiguously able to do so.

For termini, I'm not sure if we decided whether to model on trivial missing
residues. Presumably, omission in model building suggested the residues are
too mobile to resolve, which would suggest they should be capped instead of
modeled and zwitterionic, since this could make it much harder to converge
the calculations.

What do you folks think? @ppxasjsm?

2022-07-15 10:33 UTC, IAlibay commented
@jchodera My 2 cents here - cap unresolved termini, don't cap if you have the full construct.

2022-07-15 10:34 UTC, jchodera commented
This certainly sounds like the most straightforward approach for now!

2022-07-21 16:00 UTC, IAlibay commented
Just came up with another issue - the ligand SDF files don't have end blocks (i.e. `M  END` entries before the `$$$$`). I _think_ those are part of the format? (assuming the SDF format is an extension of the MDL one, and then even then the "format" is just what I can find on wikipedia...)

2022-07-21 16:03 UTC, bobym commented
> Just came up with another issue - the ligand SDF files don't have end blocks (i.e. `M END` entries before the `$$$$`). I _think_ those are part of the format? (assuming the SDF format is an extension of the MDL one, and then even then the "format" is just what I can find on wikipedia...)

@IAlibay Is this for the combined `ligands.sdf` file or the individual ligand SDFs?

2022-07-21 16:08 UTC, bobym commented
> Just came up with another issue - the ligand SDF files don't have end blocks (i.e. `M END` entries before the `$$$$`). I _think_ those are part of the format? (assuming the SDF format is an extension of the MDL one, and then even then the "format" is just what I can find on wikipedia...)

@IAlibay I just checked in `protein-ligand-benchmark/data/bace_p2/02_ligands/lig_29_L/crd/lig_29_L.sdf` and I can see the `M END` entry in line 112. Everything else before the `$$$$` are additional data fields that are related to the docking and ligand preparation done by Schrodinger. I didn't realize these would be exported -- while I doubt they would do much harm, it's probably best if we delete everything after the `M END` and before the `$$$$`

2022-07-21 16:28 UTC, IAlibay commented
> > Just came up with another issue - the ligand SDF files don't have end blocks (i.e. `M END` entries before the `$$$$`). I _think_ those are part of the format? (assuming the SDF format is an extension of the MDL one, and then even then the "format" is just what I can find on wikipedia...)
> 
> @IAlibay I just checked in `protein-ligand-benchmark/data/bace_p2/02_ligands/lig_29_L/crd/lig_29_L.sdf` and I can see the `M END` entry in line 112. Everything else before the `$$$$` are additional data fields that are related to the docking and ligand preparation done by Schrodinger. I didn't realize these would be exported by default -- while I doubt they would do much harm, it's probably best if we delete everything after the `M END` and before the `$$$$`. If it is easier, I can re-export the ligands without these fields quickly.

@bobym thanks for pointing that out, sorry hadn't seen that!

Actually I double checked with the Biovia spec sheet and it seems that these files are format compliant. I would just leave them as is in my opinion. It's either the way I squashed into a single file or a problem upstream with rdkit that needs to be fixed. In any case the choice of keeping individual files ended up quite useful.

Sorry for bothering you with this non-issue!

2022-07-27 16:41 UTC, ijpulidos commented
I encountered a minor issue with the ligands sdf files and RDKit.

If we concatenate them and try to read them using RDKit, the parsing fails (you only get one molecule). To solve this issue we would have to add a line jump between the last line with `$$$$` and the previous line. For example, the following
https://github.com/openforcefield/protein-ligand-benchmark/blob/bd860ddee3159aef87d3c86266118ee831e62cc3/data/pde10/02_ligands/lig_2750/crd/lig_2750.sdf#L218-L220
should become
```
> <s_glide_core_constrain_type> 
 snapped_core_restrain 

 $$$$ 
 ```
As far as I can tell, this only happens with RDkit  and when concatenating the files (doesn't happen if I use OpenEye to read them). It is a minor annoyance but I wonder if this is something we would like to fix to support workflows that use RDKit and need to concatenate the files.

2022-07-27 16:46 UTC, richardjgowers commented
@ijpulidos can you open an issue on rdkit about this? Seems like an easy fix and the hackathon is coming up

2022-07-27 19:12 UTC, IAlibay commented
> I encountered a minor issue with the ligands sdf files and RDKit.
> 
> If we concatenate them and try to read them using RDKit, the parsing fails (you only get one molecule). To solve this issue we would have to add a line jump between the last line with `$$$$` and the previous line. For example, the following
> 
> https://github.com/openforcefield/protein-ligand-benchmark/blob/bd860ddee3159aef87d3c86266118ee831e62cc3/data/pde10/02_ligands/lig_2750/crd/lig_2750.sdf#L218-L220
> 
> 
> should become
> ```
> > <s_glide_core_constrain_type> 
>  snapped_core_restrain 
> 
>  $$$$ 
> ```
> 
> As far as I can tell, this only happens with RDkit and when concatenating the files (doesn't happen if I use OpenEye to read them). It is a minor annoyance but I wonder if this is something we would like to fix to support workflows that use RDKit and need to concatenate the files.

@ijpulidos Yeah this is the same issue as https://github.com/openforcefield/protein-ligand-benchmark/pull/52#issuecomment-1191666055

I checked with the format spec and the SDF files are definitely standard compliant, so this is an RDKit failure.

2022-08-02 16:16 UTC, dotsdl commented
The SDF spacing issue with `$$$$` may be a consequence of my splitting approach for the all ligand SDF's @bobym produced. Will verify this.

2022-08-02 16:16 UTC, dotsdl commented
From @ijpulidos: https://github.com/rdkit/rdkit/issues/5467

2022-08-02 16:28 UTC, IAlibay commented
@ijpulidos I was super convinced I was getting this issue even when standard compliant, but I just double checked and it that doesn't seem to be the case.

We should just add in that extra blank line - @bobym do you want me to do this in #58?

2022-09-08 01:09 UTC, dotsdl commented
@IAlibay : @bobym has pushed her latest prep. Details:

> The methods are in /protein-ligand benchmark/preparation. There's a pdf with an overview, a file with the CLI commands for prep and exportation, and the ligand prep, grid generation, and docking folders for each target that includes the input files, execution scripts, logs, and results. Anyone with Schrodinger would be able to use the input files to setup their own

I believe you're already in the loop, but wanted to ask if you're good to review? Is there anything you'd like me to take on?

2022-09-08 01:16 UTC, IAlibay commented
@dotsdl yes @bobym has indeed kept me in the loop here. I'll review and will implement any #58 fixes as necessary. I'm not back from leave until the 14th so I can't guarantee I'll be able to action things until then.

2022-09-08 14:36 UTC, bobym commented
> We should just add in that extra blank line - @bobym do you want me to do this in https://github.com/openforcefield/protein-ligand-benchmark/pull/58?

Is this still an issue? If so, can you check with these files from CDK2, which I split in Maestro during export:
[cdk2_ligs.zip](https://github.com/openforcefield/protein-ligand-benchmark/files/9527758/cdk2_ligs.zip)

2022-09-08 14:42 UTC, IAlibay commented
> > We should just add in that extra blank line - @bobym do you want me to do this in #58?
> 
> @IAlibay @ijpulidos @dotsdl Is this still an issue? If so, can you check with these files from CDK2, which I split in Maestro during export: [cdk2_ligs.zip](https://github.com/openforcefield/protein-ligand-benchmark/files/9527758/cdk2_ligs.zip)

For the few sdfs I've checked for now I think it's fine, or at least the multi-ligand SDF files load fine in RDKit. I'll check the rest as I go along.

2022-09-14 03:28 UTC, ijpulidos commented
As discussed in the meeting earlier today, I noticed some changes in the number of ligands with the last commit. I run a simple script that checks this by counting the number of `sdf` files in the previous commit (revision `bd860dde`)  and comparing that to the number of ligands from the merged `sdf` file in the latest commit (revision `c339a12c`), for each target. The results are as follows:
```
Target: hif2a
    at revision bd860dde: 37, at revision c339a12c: 37
Target: cmet
    at revision bd860dde: 5, at revision c339a12c: 4
Target: syk
    at revision bd860dde: 43, at revision c339a12c: 46
Target: pfkfb3
    at revision bd860dde: 33, at revision c339a12c: 38
Target: mcl1
    at revision bd860dde: 24, at revision c339a12c: 25
Target: eg5
    at revision bd860dde: 27, at revision c339a12c: 28
Target: p38
    at revision bd860dde: 29, at revision c339a12c: 31
Target: pde2
    at revision bd860dde: 20, at revision c339a12c: 21
Target: cdk2
    at revision bd860dde: 10, at revision c339a12c: 9
Target: cdk8
    at revision bd860dde: 31, at revision c339a12c: 32
Target: thrombin
    at revision bd860dde: 11, at revision c339a12c: 10
Target: tnks2
    at revision bd860dde: 27, at revision c339a12c: 26
Target: tyk2
    at revision bd860dde: 13, at revision c339a12c: 14
Target: shp2
    at revision bd860dde: 20, at revision c339a12c: 25
Target: ptp1b
    at revision bd860dde: 22, at revision c339a12c: 22
```
While most of the targets gain ligands (this should be fine), you can see some of them losing one of the ligands, namely `cmet`, `cdk2`, `thrombin`, and `tnks2`. This may be expected. @bobym I appreciate your input here since you probably know why this is the case.

The script I run for this is in https://gist.github.com/ijpulidos/3260d15ae2c4ff06afecc7256eef94eb

I suggest using the script in an independent and fresh clone of the repo, since I already nuked my local copy by interrupting it in just the "right" instant (seems like git can be susceptible to corruption by interrupting checkouts this way), you would run it using:

```bash
python ~/workdir/snippets/check_n_ligands_plbenchmarks.py bd860dde c339a12c 2> /dev/null
```
I'm redirecting the stderr to null to avoid printing noise.

2022-09-27 14:41 UTC, ijpulidos commented
As previously discussed, I tried running all the benchmarks dataset with perses/openmm, and as far as I can see, there are 3 targets that are showing some issues:

* MCL1: `ValueError: No template found for residue 151 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.`
* PFKFB3: `ValueError: No template found for residue 449 (POP).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.`
* THROMBIN: `ValueError: No template found for residue 271 (TYS).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.`

2022-09-27 15:02 UTC, IAlibay commented
All three should be addressed by the updates I'm working on. Or at least the PDBs will make it clear with HETATM residues in cases where there are non standard residues.

2022-09-27 15:03 UTC, IAlibay commented
Also @ijpulidos I was under the impression that the OpenFE team was tasked with running these? I'd like to avoid duplication of effort (and duplication of John's cluster time) where possible.

2022-09-30 22:31 UTC, dotsdl commented
Just noticed that as of the latest commit we no longer have `bace`, `bace_hunt`, `bace_p2`, and `pde10` as targets. I may have missed this in conversation, but wanted to check that this is intended and expected?

2022-10-03 14:10 UTC, bobym commented
> Just noticed that as of the latest commit we no longer have `bace`, `bace_hunt`, `bace_p2`, and `pde10` as targets. I may have missed this in conversation, but wanted to check that this is intended and expected?

@dotsdl Yes this is expected. The short version is that the preparation of the BACE datasets in our previous and other groups' benchmarking studies has been very far off of assay conditions (assay at pH 4-5, prep at pH 7), which we decided was far off enough to have deleterious effects on the protonation states of the proteins and ligands. PDE10 was exclused because the assays were run using rat PDE10 (maybe mouse? either way, not human), while the crystal structure was of human PDE10. We decided to remove these systems for now until we can validate their preparation and assay conditions. I believe the plan was to include them in the next set, where we will be prepping all systems according to their assay conditions rather than at a specific pH.

2022-10-03 23:57 UTC, dotsdl commented
Awesome, thanks @bobym! This sufficiently jogged my memory from our previous discussions!

2022-10-07 15:49 UTC, merged

2022-10-07 15:50 UTC, IAlibay commented
Having discussed this with @dotsdl, there are some issues that need addressing, we will raise relevant issues in a short while. This should lessen the burden of dealing with a giant PR.